# Generated by Django 4.2 on 2023-04-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_rename_food_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='age_range',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='club',
            name='contact_person',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='club',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='club',
            name='tags',
            field=models.CharField(default='', max_length=200),
        ),
    ]
