# Generated by Django 4.2 on 2023-04-06 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_alter_club_id_studentclublikes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentClubLikes',
        ),
    ]
